language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone git://github.com/n1k0/casperjs.git"
  - "cd casperjs"
  - "git checkout tags/0.6.5"
  - "sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs"
  - "RAILS_ENV=test bundle exec rake app:db:schema:load"

script: "bundle exec rake"

gemfile:
  - "gemfiles/rails_3_1.gemfile"
  - "gemfiles/rails_3_2.gemfile"
  - "gemfiles/rails_4.gemfile"

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: "gemfiles/rails_4.gemfile"
